### ISSUE TITLE
 Cannot find module 'finalhandler'

### ISSUE THREAD

**Issue by ozz-project** [shen139/openwebspider#2]
Hi,
i tried to start the Server under Windows with node6. MySQL is installed but by running the Batch file i got this error.

> C:\Users\nope\Desktop\6>node src/server.js
> module.js:471
>     throw err;
>     ^
> 
> Error: Cannot find module 'finalhandler'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\Users\nope\Desktop\6\src\server.js:3:20)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)

**Comment by shen139** [comment]
Try with:

```sh
npm install
```

The package "finalhandler" is included in the package.json.
If it doesn't work try with:
```sh
npm install finalhandler
```

**Comment by ozz-project** [comment]
Thx.
Now its fine.
